---
- name: Set static IP using netplan (for Linux machines in general, no gateway)
  hosts: linux
  become: yes
  vars:
    interface_name: ens19
    dns_servers: ["172.16.217.5", "172.16.217.6"]

  tasks:
    - name: Create Netplan configuration file
      copy:
        dest: /etc/netplan/01-netcfg.yaml
        content: |
          network:
            version: 2
            ethernets:
              {{ interface_name }}:
                dhcp4: false
                addresses:
                  - "{{ static_ip }}"
                nameservers:
                  addresses: {{ dns_servers }}
        mode: '0644'

    - name: Apply Netplan configuration
      command: netplan apply
