---
- name: Set static IP using nmcli (for Kali or NetworkManager-based systems)
  hosts: Audit-Control-01
  become: yes
  vars:
    interface_name: eth1
    connection_name: "Wired connection 2"
    dns_servers: ["172.16.217.5", "172.16.217.6"]

  tasks:
    - name: Check if the connection exists
      shell: nmcli -t -f NAME con show | grep -w "{{ connection_name }}"
      register: con_check
      ignore_errors: true

    - name: Create connection if it does not exist
      shell: nmcli con add type ethernet ifname {{ interface_name }} con-name "{{ connection_name }}"
      when: con_check.rc != 0

    - name: Configure static IP on {{ connection_name }} using nmcli (no gateway)
      shell: >
        nmcli con mod "{{ connection_name }}"
        ipv4.addresses {{ static_ip }}
        ipv4.dns "{{ dns_servers | join(',') }}"
        ipv4.method manual

    - name: Bring interface up
      shell: nmcli con up "{{ connection_name }}"